config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :accounts
  resources :playlists
  get "/play/:playlist_id", to: "playlists#add_movies", as: "adding"

  root 'movies#index'
  get '/genre/:genre', to: 'movies#show_genre', as: 'genre'

  resources :movies do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :comments

  def add_to_playlist
    binding.pry
  end

  def remove_playlist
    binding.pry
  end

end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :movies

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :update, :destroy]

  def index
    @accounts = current_user.accounts
  end

  def show
  end

  def new
    @account = Account.new
  end

  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
        redirect_to accounts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @account.update(account_params)
      redirect_to_path
    else
      render :edit
    end
  end

  def destroy
  end

  private
    def account_params
      params.require(:account).permit(:name)
    end

    def set_account
      @account = current_user.accounts.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name ])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_movie
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    #TODO user_profile
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = @movie.comments.new(comment_params)

    if @comment.save
      redirect_to movie_path(@movie)
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to movie_path(@movie)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def show_genre
    @genre = Movie.where(genre: params[:genre])
  end

  def show
  end

  def index
    @movies = Movie.all
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to '/'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to '/'
  end

  def new
    @movie = Movie.new
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :duration, :genre, :description, :trailer)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  
  
  def index
    @playlists= Playlist.where(user_id: current_user.id) 
  end

  def add_movies
    @movies = Movie.all
  end

  def show
    @playlist = Playlist.find(params[:id])
    @movies = Movie.where(playlist_id: @playlist.id)
  end

  def new
    @playlist = Playlist.new 
  end
  def create
    @playlist = Playlist.new(user_id: current_user.id, name: params["playlist"]["name"])

    if @playlist.save
      redirect_to playlists_path
    else
      render :new
    end

  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy 
    redirect_to playlists_path
  end
  private  
  
  def playlist_params
    params.require(:playlist).permit(:name, :user_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

app/views/accounts/index.html.erb
<h1>Accounts#index</h1>

app/views/accounts/new.html.erb
<h1>Accounts#new</h1>
<p>Find me in app/views/accounts/new.html.erb</p>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

app/views/comments/_form.html.erb
<h1><%= @comment.id ? 'Edit Comment' : 'Add Comment' %></h1>
<br />
<div class="ui form">
  <%= form_for [@movie, @comment] do |f| %>
  <div class="field">
  <h3><%= f.label :body %></h3>
  <%= f.text_area :body, required: true %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Submit", :class => 'ui tiny button' %>
  </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/show.html.erb
<br />
<br />
<h1><%= current_user.first_name %> <%= current_user.last_name %></h1>
<p><%= @comment.body %></p>
<% movie = @movie.id.to_i %>
<% comment = @comment.id.to_i %>
<%= link_to 'Edit Comment', edit_movie_comment_path %> /
<%= link_to 'Delete Comment', movie_comment_path[movie, comment], method: :delete %> /
<%= link_to 'Back', movie_path(movie) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utoob</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Voltaire" rel="stylesheet">
  </head>

  <body>
    <div class="fixed ui center aligned container">
      <br />
      <img src="https://vignette.wikia.nocookie.net/logopedia/images/1/1b/Movie_Central.png/revision/latest?cb=20100816062904" width='400' height='200' />
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<h1><%= @movie.id ? 'Edit Movie' : 'Add Movie' %></h1>
<div class="ui form">
<br />
<%= form_for @movie do |f| %>
  <div class="field">
  <%= f.label :genre %>
  <%= f.select :genre, ['Drama', 'Comedy', 'Action'] %>
  </div>
  <div class="field">
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>
  </div>
  <div class="field">
  <%= f.label :duration %>
  <%= f.text_field :duration, required: true %>
  </div>
  <div class="field">
  <%= f.label :description %>
  <%= f.text_field :description, required: true %>
  </div>
  <div class="field">
  <%= f.label :trailer %>
  <p>Please enter the embedded link for the trailer/movie.</p>
  <%= f.text_field :trailer, required: true %>
  </div>
  <hr />
  <br />
  <div class="actions">
  <%= f.submit "Submit", :class => 'ui tiny button' %>
  </div>
  <br />
  <br />
</div>
<% end %>

app/views/movies/edit.html.erb
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Welcome <%= current_user.first_name %>!</h1>
<%= button_to 'Profile', playlists_path, method: :get, class: 'ui tiny button' %>
<br />
<%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: 'ui tiny button' %>

<h3>Which Genre of Movies Do You Want To View?</h3>
<% genre = @movies.distinct.pluck(:genre) %>
<% genre.each do |m| %>
    <%= link_to m, genre_path(genre: m) %>
    <br />
<% end %>
<br />
<hr />
<h5>Want To Add Your Own Movie?</h5>
<%= link_to 'Click Here', new_movie_path %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<h4>Genre: <%= @movie.genre %> <br /> Duration: <%= @movie.duration %></h4>
<iframe src="<%= @movie.trailer %>" width="720" height="480"></iframe>
<br />
<br />
<a href="<%= @movie.description%>" target="_blank">IMDB Profile</a>
<br />
<br />
<%= link_to 'Edit Movie', edit_movie_path(@movie) %> / 
<%= link_to 'Remove Movie', @movie, method: :delete %> /
<%= link_to 'Create Comment', new_movie_comment_path(@movie) %> /
<%= link_to 'Back', movies_path %>
<hr />
<br />
<% @movie.comments.each do |comment| %>
<div class="label">
  <i class="pencil icon"></i>
<p><%= comment.body %> - <%= current_user.first_name %> <%= current_user.last_name %><br /><%= link_to 'Show', movie_comment_path(@movie, comment) %></p>
<% end %>
</div>
<br />
<br />

app/views/movies/show_genre.html.erb
<h1><%= @genre.first.genre %></h1>
<hr />
<% @genre.each do |movie| %>
<h3><%= link_to movie.title, movie_path(movie) %></h3>
<% end %>
<br />
<hr />
<h3><%= link_to 'Back', movies_path %></h3>
<br />
<br />
  

app/views/playlists/_form.html.erb
<h1><%= @playlist.id ? 'Edit Playlist' : 'Add Playlist' %></h1>
<br />
<div class="ui form">
<%= form_for [@playlist] do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_area :name, required: true %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Submit", :class => 'ui tiny button' %>
  </div>
<% end %>
</div>

app/views/playlists/add_movies.html.erb
<% @movies.each do |m| %>
  <% if m.playlist_id.to_s == params[:playlist_id]%>
    <h3><%= m.title %></h3>
    <button> Remove From List </button>
  <% else %>
    <h3><%= m.title %></h3>
    <button> Add To List </button>
  <% end %>
<% end %>

app/views/playlists/index.html.erb
<h1>Playlists</h1>
<%= link_to "Create New Playlist", new_playlist_path %>
<% @playlists.each do |p| %>
<p><%= link_to p.name, playlist_path(p) %></p>
<% end %>

app/views/playlists/new.html.erb
<%= render 'form' %>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>
<%= link_to "Delete Playlist", playlist_path(@playlist), method: :delete %>
<%= link_to "Add Movies To Playlist", adding_path(@playlist.id) %>
<% @movies.each do |m| %>
<p><%= m.title %></p>
<% end %>